#include <iostream>

using namespace std;

int main()
{
    char a='A',b='B',c='C',d='D',e='E',f='F',g='G',h='H',i='I',j='J',k='K',l='L',m='M',n='N',o='O',p='P',q='Q',r='R',s='S',t='T',u='U',v='V',w='W',x='X',y='Y',z='Z';
    char A='a',B='b',C='c',D='d',E='e',F='f',G='g',H='h',I='i',J='j',K='k',L='l',M='m',N='n',O='o',P='p',Q='q',R='r',S='s',T='t',U='u',V='v',W='w',X='x',Y='y',Z='z';
    char let;

    cout<<"Enter letter:"<<endl;
    cin>>let;

    if(let==a){
        cout<<A<<endl;
    }
    if(let==b){
        cout<<B<<endl;
    }
    if(let==c){
        cout<<C<<endl;
    }
    if(let==d){
        cout<<D<<endl;
    }
    if(let==e){
        cout<<E<<endl;
    }
    if(let==f){
        cout<<F<<endl;
    }
    if(let==g){
        cout<<G<<endl;
    }
    if(let==h){
        cout<<H<<endl;
    }
    if(let==i){
        cout<<I<<endl;
    }
    if(let==j){
        cout<<J<<endl;
    }
    if(let==k){
        cout<<K<<endl;
    }
    if(let==l){
        cout<<L<<endl;
    }
    if(let==m){
        cout<<M<<endl;
    }
    if(let==n){
        cout<<N<<endl;
    }
    if(let==o){
        cout<<O<<endl;
    }
    if(let==p){
        cout<<P<<endl;
    }
    if(let==q){
        cout<<Q<<endl;
    }
    if(let==r){
        cout<<R<<endl;
    }
    if(let==s){
        cout<<S<<endl;
    }
    if(let==t){
        cout<<T<<endl;
    }
    if(let==u){
        cout<<U<<endl;
    }
    if(let==v){
        cout<<V<<endl;
    }
    if(let==w){
        cout<<W<<endl;
    }
    if(let==x){
        cout<<X<<endl;
    }
    if(let==y){
        cout<<Y<<endl;
    }
    if(let==z){
        cout<<Z<<endl;
    }
    if(let==A){
        cout<<a<<endl;
    }
    if(let==B){
        cout<<b<<endl;
    }
    if(let==C){
        cout<<c<<endl;
    }
    if(let==D){
        cout<<d<<endl;
    }
    if(let==E){
        cout<<e<<endl;
    }
    if(let==F){
        cout<<f<<endl;
    }
    if(let==G){
        cout<<g<<endl;
    }
    if(let==H){
        cout<<h<<endl;
    }
    if(let==I){
        cout<<i<<endl;
    }
    if(let==J){
        cout<<j<<endl;
    }
    if(let==K){
        cout<<k<<endl;
    }
    if(let==L){
        cout<<l<<endl;
    }
    if(let==M){
        cout<<m<<endl;
    }
    if(let==N){
        cout<<n<<endl;
    }
    if(let==O){
        cout<<o<<endl;
    }
    if(let==P){
        cout<<p<<endl;
    }
    if(let==Q){
        cout<<q<<endl;
    }
    if(let==R){
        cout<<r<<endl;
    }
    if(let==S){
        cout<<s<<endl;
    }
    if(let==T){
        cout<<t<<endl;
    }
    if(let==U){
        cout<<u<<endl;
    }
    if(let==V){
        cout<<v<<endl;
    }
    if(let==W){
        cout<<w<<endl;
    }
    if(let==X){
        cout<<x<<endl;
    }
    if(let==Y){
        cout<<y<<endl;
    }
    if(let==Z){
        cout<<z<<endl;
    }
    return 0;
}
